"""Table for pydantic & project fixes

Revision ID: cbd8239ae1b7
Revises: b01941f39347
Create Date: 2024-06-23 00:18:11.021935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd8239ae1b7'
down_revision: Union[str, None] = 'b01941f39347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pydantic',
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('classname', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filepath', 'classname')
    )
    op.drop_constraint('explanation_project_id_fkey', 'explanation', type_='foreignkey')
    op.create_foreign_key(None, 'explanation', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'explanation', type_='foreignkey')
    op.create_foreign_key('explanation_project_id_fkey', 'explanation', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_table('pydantic')
    # ### end Alembic commands ###
